export {
  TisAccordionHarness,
  TisBadgeHarness,
  TisButtonHarness,
  TisCheckboxHarness,
  TisComboboxHarness,
  TisInputHarness,
  TisMenuHarness,
  TisModalHarness,
  TisPopoverHarness,
  TisRadioGroupHarness,
  TisSelectHarness,
  TisTabsHarness,
  TisTextareaHarness,
  TisToastHarness,
  TisToggleHarness,
  TisTooltipHarness,
} from "./harnesses";
